server:
  port: 0
  address: 127.0.0.1
  shutdown: graceful

spring:
  main:
    lazy-initialization: true
  web:
    resources:
      add-mappings: false
  lifecycle:
    timeout-per-shutdown-phase: 10s

claw:
  home: ${user.home}/.c-claw

anthropic:
  base-url: http://172.21.197.208:8080/efllmas-agw/anthropicproxy
  model-name: kimi-k2.5-aliyun
  key: sk-zht_dev_adamcchen

logging:
  charset:
    console: UTF-8
  level:
    cc.claw: DEBUG